server:
  port: 7001


eureka:
  instance:
    #eureka服务端的实例名称
    hostname: eureka7001.com
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心,职责是维护实例,并不需要检索服务
    fetch-registry: false
    service-url:
      #设置与Eureka Server 交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://eureka7002.com:7002/eureka/  #集群指向其他eureka
    server:
      #关闭自我保护机制，保证不可用服务被及时剔除.默认开启保护机制 true
      enable-self-preservation: false
      #清理无效节点的时间间隔 默认60000毫秒，即60秒
      eviction-interval-timer-in-ms: 2000


